version: "3"

services:
  rabbit:
    container_name: rain-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped

  nginx:
    container_name: rain-nginx
    build: ./nginx
    links:
      - app:app
    ports:
      - 3000:3000
    depends_on:
      - app
    restart: unless-stopped

  app:
    container_name: rain-app
    build: .
    depends_on:
      - rabbit
      - db
    links:
      - rabbit:rabbit
      - db:db
    ports:
      - 8080:8080
    restart: unless-stopped

  worker:
    container_name: rain-worker
    build:
      context: .
      dockerfile: Workerdocker
    depends_on:
      - rabbit
      - db
    links:
      - rabbit:rabbit
      - db:db
    restart: unless-stopped

  db:
    container_name: rain-postgres
    build: ./postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/etc/postgresql
      - postgres_log:/var/log/postgresql
      - postgres_lib:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres_volume:
  postgres_log:
  postgres_lib:
